name: pratvi_web
description: Website for Rutvi & Pranay's Wedding

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_300.ttf
          weight: 300
        - asset: assets/fonts/montserrat_400.ttf
          style: normal
        - asset: assets/fonts/montserrat_500.ttf
          weight: 500
        - asset: assets/fonts/montserrat_600.ttf
          weight: 600
        - asset: assets/fonts/montserrat_700.ttf
          weight: 700
    - family: script
      fonts:
        - asset: assets/fonts/script_500.ttf
          weight: 500
        - asset: assets/fonts/script_600.ttf
          weight: 600

  assets:
    - assets/
    - assets/images/
    - assets/anim/